name: Multi-21, Seb
on:
  push:
    branches:
      - main
      - staging
jobs:
  terraform:
    name: Terraform infrastructure
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Format Terraform configuration
        working-directory: ./terraform
        run: terraform fmt

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: ./terraform
        run: terraform validate

      - name: Select STAGING workspace
        if: ${{ github.ref == 'refs/heads/staging' && github.event_name == 'push' }}
        working-directory: ./terraform
        run: terraform workspace select staging

      - name: Select PRODUCTION workspace
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        working-directory: ./terraform
        run: terraform workspace select production

      - name: Plan Terraform configuration
        working-directory: ./terraform
        run: terraform plan -no-color

      - name: Apply Terraform configuration
        working-directory: ./terraform
        run: terraform apply -auto-approve
